import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";

import "./global.css";
import Header from "./components/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Base de Dados",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="container flex flex-col mx-auto">
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
